# Generated by Django 5.2.3 on 2025-07-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_activity_certificate_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
