# Generated by Django 5.2.3 on 2025-07-16 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('level', models.CharField(default='Beginner', max_length=50)),
                ('forma', models.CharField(default='Video', max_length=50)),
                ('what_you_will_learn', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('instructor_title', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.course')),
            ],
        ),
    ]
