# Generated by Django 5.2.3 on 2025-07-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_coursedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetails',
            name='instructor_title',
        ),
    ]
