# Generated by Django 5.2.3 on 2025-07-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_coursedetails_instructor_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='what_you_will_learn',
            field=models.JSONField(default=list),
        ),
    ]
