# Generated by Django 5.2.3 on 2025-07-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_coursedetails_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='curriculum',
            field=models.JSONField(default=list),
        ),
    ]
