# Generated by Django 5.2.3 on 2025-07-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_enrollment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
