# Generated by Django 5.2.3 on 2025-07-19 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_enrollment_is_enrolled'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='instructor_profiles/default.jpg', upload_to='instructor_profiles/')),
                ('bio', models.TextField(blank=True, help_text="Instructor's biography and teaching philosophy")),
                ('specialty', models.CharField(blank=True, help_text='Main area of expertise', max_length=200)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('education', models.TextField(blank=True, help_text='Educational background')),
                ('certifications', models.TextField(blank=True, help_text='Professional certifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
