# Generated by Django 5.2.3 on 2025-07-19 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_instructorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetails',
            name='bio',
        ),
    ]
