# Generated by Django 5.2.3 on 2025-07-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_coursedetails_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('enrollment', 'Enrollment'), ('certificate', 'Certificate Earned'), ('profile_update', 'Profile Update'), ('login', 'Login'), ('logout', 'Logout'), ('lesson_completed', 'Lesson Completed'), ('lesson_uploaded', 'Lesson Uploaded'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='profile_picture',
            field=models.ImageField(default='profiles/default.jpg', upload_to='instructor_profiles/'),
        ),
    ]
