# Generated by Django 5.2.3 on 2025-07-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
    ]
