# Generated by Django 5.2.3 on 2025-08-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('enrollment', 'Enrollment'), ('certificate', 'Certificate Earned'), ('profile_update', 'Profile Update'), ('login', 'Login'), ('logout', 'Logout'), ('lesson_completed', 'Lesson Completed'), ('lesson_uploaded', 'Lesson Uploaded'), ('announcement_created', 'Announcement Created'), ('announcement_updated', 'Announcement Updated'), ('announcement_deleted', 'Announcement Deleted'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
